[package]
name = "fuzz_from_str"
version = "0.1.0"
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
rand = "0.8.5"
libfuzzer-sys = "0.4"
regex = "1.9.4"
chrono = "0.4"

[dependencies.parse_datetime]
path = "../"

[[bin]]
name = "fuzz_from_str"
path = "fuzz_targets/from_str.rs"
test = false
doc = false

[[bin]]
name = "fuzz_parse_datetime_from_str"
path = "fuzz_targets/parse_datetime_from_str.rs"
test = false
doc = false
